// Generated by https://quicktype.io

export interface ResultCancioneros {
  ok:         boolean;
  msg:        string;
  cancionero: Cancionero[];
}

export interface Cancionero {
  ids:    number;
  id:     number;
  nombre: string;
  logo:   string;
  estado: number;
}
