// Generated by https://quicktype.io

export interface ResultDirectorios {
  ok:         boolean;
  msg:        string;
  directorio: Directorio[];
}

export interface Directorio {
  ids:       number;
  id:        number;
  nombre:    string;
  telefono:  string;
  direccion: string;
  lat:       number;
  lng:       number;
  logo:      string;
  imagen:    string;
  social:    string;
  estado:    number;
}

export interface DirectorioForm{
  nombre:string,
  telefono?:string,
  direccion:string,
  logo:string,
  archivo:string,
  social?:string
}
