// Generated by https://quicktype.io

export interface ResultHorarios {
  ok:      boolean;
  msg:     string;
  horario: Horario[];
}

export interface Horario {
  id:          number;
  descripcion: string;
  estado:      number;
}
