// Generated by https://quicktype.io

export interface ResultLiturgias {
  ok:       boolean;
  msg:      string;
  liturgia: Liturgia[];
}
export interface ResultLiturgia {
  ok:       boolean;
  msg:      string;
  liturgia: Liturgia;
}
export interface Liturgia {
  id:     number;
  nombre: string;
  logo:   string;
  estado: number;
}
export interface LiturgiaForm{
  nombre?:string,
  logo?:string
}
