// Generated by https://quicktype.io

export interface ResultMaterialPastorales {
  ok:       boolean;
  msg:      string;
  material: Material[];
}
export interface ResultMaterialPastoral {
  ok:       boolean;
  msg:      string;
  material: Material;
}
export interface Material {
  id:     number;
  nombre: string;
  logo:   string;
  estado: number;
}

export interface MaterialForm{
  nombre:string,
  logo?:string,
}

export interface LogoMaterialForm{
  logo?:string,
  pdf?:string
}

