// Generated by https://quicktype.io

export interface ResultNoticiaImagen {
  ok:         boolean;
  msg:        string;
  notiImagen: NotiImagen[];
}

export interface NotiImagen {
  id:         number;
  nombre:     string;
  id_noticia: number;
}
