// Generated by https://quicktype.io

export interface ResultOraciones {
  ok:        boolean;
  msg:       string;
  oraciones: Oracione[];
}

export interface Oracione {
  id:       number;
  nombre:   string;
  multiple: number;
  logo:     string;
  estado:   number;
}
