// Generated by https://quicktype.io

export interface ResultTipoDirectorios {
  ok:             boolean;
  msg:            string;
  tipoDirectorio: TipoDirectorio[];
}

export interface TipoDirectorio {
  id:     number;
  nombre: string;
  estado: number;
}
