// Generated by https://quicktype.io

export interface ResultAuth {
    ok:    boolean;
    msg:   string;
    user:  User;
    token: string;
}

export interface User {
    id:       number;
    usuario:  string;
    password: string;
    estado:   number;
}
